services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "$MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 5

  store:
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    image: book-store
    env_file: ./.env
    ports:
      - "$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT"
      - "$DEBUG_PORT:$DEBUG_PORT"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE
      SPRING_DATASOURCE_USERNAME: $MYSQLDB_USER
      SPRING_DATASOURCE_PASSWORD: $MYSQLDB_PASSWORD
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

